#ipAddr: 127.0.0.1
#spring:
#  application:
#    name: gulimall-product
#  datasource:
#    username: root
#    password: mq0000
#    url: jdbc:mysql://${ipAddr}:3306/mall_pms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
##    loadbalancer:
##      ribbon:
##        enable: false
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8333
#  # 指定返回时间的格式化
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  thymeleaf:
#    cache: false
#    suffix: .html
#    prefix: classpath:/templates/
#  session:
#    store-type: redis
#  redis:
#    host: ${ipAddr}
##   设置缓存类型
#  cache:
#    type: redis
##   设置存活时间
#    redis:
#      time-to-live: 3600000
##      如果指定了前缀就用我们指定的 如果没有就用缓存的名字作为前缀
##      key-prefix: CACHE_
##      是否缓存空值
#      cache-null-values: true
#  main:
#    allow-bean-definition-overriding: true
##      sleuth和zipkin链路追踪配置
##  sleuth:
##    sampler:
##    设置抽样采集率为100%，默认为0.1，采集率表示链路追踪的数据采集百分比
##      probability: 1
##  zipkin:
##  zipkin服务器的地址
##    base-url:
##   关闭服务发现，否则springcloud会把zipkin的url当成服务器名称处
##    discovery-client-enabled: false
##   采用什么方式传输数据
##    sender:
##      type: web
#
#
##    cache-names:
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      # 配置逻辑删除 1代表删除 0代表已删除
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#server:
#  port: 10001
#logging:
#  level:
#    com.atguigu.gulimall.product: error
##    org.springframework.cloud.openfeign: debug
##    org.springframework.cloud.sleuth: debug
#
#ribbon:
#  ReadTimeout: 30000
#  ConnectTimeout: 30000
#
#gulimall:
#  thread:
#    core-size: 20
#    max-size: 200
#    keep-alive-time: 10